#!/bin/sh /etc/rc.common
# /etc/init.d/sing-box

START=95
STOP=15
USE_PROCD=1

PROG=/usr/bin/sing-box
CONF=/etc/sing-box/config.json

start_service() {
    [ -f "$CONF" ] || return 0
    mkdir -p /var/lib/sing-box
    procd_open_instance sing-box
    procd_set_param command "$PROG" run -c "$CONF"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "sing-box"
}
